### ISSUE TITLE
Readme example tools

### ISSUE THREAD

**Issue by softprops** [benjojo/traceroute-haiku#2]
Love your readme. What software did you use to generate this awesome gif?
 https://github.com/benjojo/traceroute-haiku/blob/master/blog-images/trace.gif

**Comment by benjojo** [comment]
> Love your readme

Thanks! It's actually just the mirror of the blog post, if you like that, you may like my others! blog.benjojo.co.uk

> What software did you use to generate this awesome gif?

It's hand made, You can find the GIMP project files here: https://github.com/benjojo/traceroute-haiku/tree/master/blog-images/gif

**Comment by softprops** [comment]
Awesome. Such a cool project!
